"""System enums and domain constants."""
from enum import Enum

class BotState(str, Enum):
    RUNNING = "RUNNING"
    PAUSED = "PAUSED"
    EMERGENCY_STOP = "EMERGENCY_STOP"

class OrderSide(str, Enum):
    BUY = "BUY"
    SELL = "SELL"
    CLOSE = "CLOSE"
    MODIFY = "MODIFY"

class PositionSide(str, Enum):
    LONG = "LONG"
    SHORT = "SHORT"

class PositionStatus(str, Enum):
    OPEN = "OPEN"
    CLOSED = "CLOSED"
    PARTIALLY_CLOSED = "PARTIALLY_CLOSED"

class OrderStatus(str, Enum):
    PENDING = "PENDING"
    FILLED = "FILLED"
    PARTIAL = "PARTIAL"
    REJECTED = "REJECTED"
    CANCELLED = "CANCELLED"
    UNCERTAIN = "UNCERTAIN"

class SignalStatus(str, Enum):
    PENDING = "PENDING"
    VALIDATED = "VALIDATED"
    REJECTED_SESSION = "REJECTED_SESSION"
    REJECTED_RISK = "REJECTED_RISK"
    REJECTED_DUPLICATE = "REJECTED_DUPLICATE"
    EXECUTED = "EXECUTED"
    FAILED = "FAILED"

class WebhookStatus(str, Enum):
    RECEIVED = "RECEIVED"
    VALIDATED = "VALIDATED"
    DUPLICATE = "DUPLICATE"
    PROCESSED = "PROCESSED"
    REJECTED = "REJECTED"
    FAILED = "FAILED"

class ExitReason(str, Enum):
    TAKE_PROFIT = "TAKE_PROFIT"
    STOP_LOSS = "STOP_LOSS"
    TRAILING_STOP = "TRAILING_STOP"
    SIGNAL_CLOSE = "SIGNAL_CLOSE"
    EMERGENCY_STOP = "EMERGENCY_STOP"
    MANUAL = "MANUAL"

class RiskEventType(str, Enum):
    DAILY_LOSS_BREACH = "DAILY_LOSS_BREACH"
    MAX_DRAWDOWN_LIMIT = "MAX_DRAWDOWN_LIMIT"
    SPREAD_EXCEEDED = "SPREAD_EXCEEDED"
    CONSECUTIVE_LOSS_PAUSE = "CONSECUTIVE_LOSS_PAUSE"
    INVALID_LOT_SIZE = "INVALID_LOT_SIZE"
    MARGIN_CALL_PROTECT = "MARGIN_CALL_PROTECT"
    BOT_STATE_RESTRICTION = "BOT_STATE_RESTRICTION"

class RiskAction(str, Enum):
    SIGNAL_REJECTED = "SIGNAL_REJECTED"
    BOT_PAUSED = "BOT_PAUSED"
    EMERGENCY_STOP_TRIGGERED = "EMERGENCY_STOP_TRIGGERED"
